# development:
#   adapter: postgresql
#   encoding: unicode
#   database: swispon
#   pool: 30
#   host: 127.0.0.1
#   username: dangnguyen
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: vinyo_wdb_dev
#   pool: 30
#   host: 127.0.0.1
#   username: vinyo
#   password:

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

production:
  database: db/production.sqlite3
